---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lcs-load-generator-serviceaccount
  namespace: <your-namespace>
rules:
  - apiGroups: ["extensions", "apps", "batch", "security.openshift.io", "policy"]
    resources: ["deployments", "jobs", "pods", "services", "jobs/status",
                "podsecuritypolicies", "securitycontextconstraints"]
    verbs: ["use", "get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lcs-load-generator-role
  namespace: <your-namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lcs-load-generator-serviceaccount
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: lcs-load-generator
  namespace: <your-namespace>
  labels:
    app: lcs-load-generator
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: lcs-load-generator
    spec:
      restartPolicy: Never
      containers:
        - name: lcs-load-generator
          image: <lcs-load-generator-image>
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          env:
            - name: KUBECONFIG
              value: "/etc/kubeconfig/kubeconfig"
            - name: LCS_NAMESPACE
              value: "<lcs-namespace>"
            - name: LCS_HOST
              value: "<lcs-host-url>"
            - name: LCS_TOKEN
              value: "<lcs-auth-token>"
            - name: LCS_PROVIDER
              value: "<llm-provider>"
            - name: LCS_MODEL
              value: "<llm-model>"
            - name: LOCUST_USERS
              value: "<concurrent-users>"
            - name: LOCUST_RUN_TIME
              value: "<test-duration>"
            - name: LOCUST_PROCESSES
              value: "<worker-processes>"
            - name: TEST_UUID
              value: ""
            - name: REQUEST_TIMEOUT
              value: "<request-timeout>"
            - name: RESULTS_DIR
              value: "/results"
            - name: QUESTIONS_FILE
              value: "/opt/lcs-load-generator/locust/assets/questions.yaml"
            - name: ES_SERVER
              value: "<es-url>"
            - name: ES_INDEX
              value: "<es-index>"
            - name: METRIC_STEP
              value: "<step-size>"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: results
              mountPath: /results
            - name: kubeconfig-volume
              mountPath: /etc/kubeconfig
              readOnly: true
          imagePullPolicy: Always
      volumes:
        - name: results
          emptyDir: {}
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig-secret
